spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

logging:
  level:
    root: INFO

mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true

